version: 2

references:
  shared: &shared
    working_directory: ~/ws-status
    steps:
      - checkout
      - run:
          name: Installing dependencies
          command: npm install
      - run:
          name: Run tests
          command: npm test
jobs:
  lint:
    docker:
      - image: circleci/node:9
    steps:
      - checkout
      - run:
          name: Installing dependencies
          command: npm install
      - run:
          name: Eslint
          command: npm run lint
  node-9:
    <<: *shared
    docker:
      - image: circleci/node:9

  node-9-browsers:
    <<: *shared
    docker:
      - image: circleci/node:9-browsers

  node-8:
    <<: *shared
    docker:
      - image: circleci/node:8

  node-8-browsers:
    <<: *shared
    docker:
      - image: circleci/node:8-browsers

  node-6:
    <<: *shared
    docker:
      - image: circleci/node:6

  node-6-browsers:
    <<: *shared
    docker:
      - image: circleci/node:6-browsers

  publish_npm_on_tag:
    <<: *shared
    docker:
      - image: circleci/node:9
    steps:
      - checkout
      - run:
          name: Authorize NPM
          command: echo "//registry.npmjs.org/:_authToken=$PRIVATE_NPM_TOKEN" > ~/.npmrc

      - run:
          name: Publish to NPM
          command: npm publish

workflows:
  version: 2
  main:
    jobs:
      - lint:
          filters:
            tags:
              only: /.*/
      - node-9:
          requires:
            - lint
          filters:
            tags:
              only: /.*/
      - node-9-browsers:
          requires:
            - lint
          filters:
            tags:
              only: /.*/
      - node-8:
          requires:
            - lint
          filters:
            tags:
              only: /.*/
      - node-8-browsers:
          requires:
            - lint
          filters:
            tags:
              only: /.*/
      - node-6:
          requires:
            - lint
          filters:
            tags:
              only: /.*/
      - node-6-browsers:
          requires:
            - lint
          filters:
            tags:
              only: /.*/
      - publish_npm_on_tag:
          requires:
            - node-9
            - node-9-browsers
            - node-8
            - node-8-browsers
            - node-6
            - node-6-browsers
          filters:
            tags:
              only: /v.*/
            branches:
              ignore: /.*/
